USE [master]
GO


/****** Object:  Database [RssNews]    Script Date: 03.09.2018 22:34:40 ******/
CREATE DATABASE [RssNews]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RssNews', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\RssNews.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RssNews_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\RssNews_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [RssNews] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RssNews].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RssNews] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RssNews] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RssNews] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RssNews] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RssNews] SET ARITHABORT OFF 
GO

ALTER DATABASE [RssNews] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RssNews] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RssNews] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RssNews] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RssNews] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RssNews] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RssNews] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RssNews] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RssNews] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RssNews] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RssNews] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RssNews] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RssNews] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RssNews] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RssNews] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RssNews] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RssNews] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RssNews] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RssNews] SET  MULTI_USER 
GO

ALTER DATABASE [RssNews] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RssNews] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RssNews] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RssNews] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RssNews] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RssNews] SET QUERY_STORE = OFF
GO

USE [RssNews]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [RssNews] SET  READ_WRITE 
GO

 CREATE TABLE News (
        PubDate              datetime NOT NULL,
        SourceId             int NOT NULL,
        Title                nvarchar(300) NOT NULL,
        Description          nvarchar(MAX) NOT NULL,
        URL                  nvarchar(2083) NOT NULL
 )
GO
 
 
 ALTER TABLE News
        ADD PRIMARY KEY NONCLUSTERED (PubDate, SourceId, Title)
GO
 
 
 CREATE TABLE RSS_source (
        Name                 nvarchar(50) NOT NULL,
        SourceId             int IDENTITY(1,1),
        URL                  varchar(50) NOT NULL
 )
GO
 
 
 ALTER TABLE RSS_source
        ADD PRIMARY KEY NONCLUSTERED (SourceId)
GO
 
 
 ALTER TABLE News
        ADD FOREIGN KEY (SourceId)
                              REFERENCES RSS_source
GO
 
 USE [RssNews]
 GO
 INSERT INTO [dbo].[RSS_source] ([Name], [URL])
 VALUES
 ('Хабрахабр', 'http://habrahabr.ru/rss/'),
 ('Интерфакс','http://www.interfax.by/news/feed')

